name = "daily-digest-chk"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[triggers]
crons = ["0 15 * * *"]

[[kv_namespaces]]
binding = "TOPICS"
id = "d25acad592b44cbc9b8160abcd5dad32"

[ai]
binding = "AI"
